// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"token_learn/internal/biz"
	"token_learn/internal/conf"
	"token_learn/internal/data"
	"token_learn/internal/server"
	"token_learn/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.Jwt, token *conf.Token, tokenV2 *conf.TokenV2, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	jwtRepo := data.NewJwtRepo(dataData, logger)
	jwtUsecase := biz.NewJwtUsecase(jwtRepo, logger)
	jwtService := service.NewJwtService(jwt, jwtUsecase)
	tokenRepo := data.NewTokenRepo(dataData, logger)
	tokenUsecase := biz.NewTokenUsecase(tokenRepo, logger)
	tokenService := service.NewTokenService(logger, token, confData, tokenUsecase)
	tokenV2Service := service.NewTokenV2Service(logger, tokenV2, confData, tokenUsecase)
	grpcServer := server.NewGRPCServer(logger, confServer, jwtService, tokenService, tokenV2Service)
	httpServer := server.NewHTTPServer(logger, confServer, jwtService, tokenService, tokenV2Service)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
