// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: token/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorTokenReason int32

const (
	ErrorTokenReason_TOKEN_UNSPECIFIED ErrorTokenReason = 0 //  USER_NOT_FOUND = 1;
)

// Enum value maps for ErrorTokenReason.
var (
	ErrorTokenReason_name = map[int32]string{
		0: "TOKEN_UNSPECIFIED",
	}
	ErrorTokenReason_value = map[string]int32{
		"TOKEN_UNSPECIFIED": 0,
	}
)

func (x ErrorTokenReason) Enum() *ErrorTokenReason {
	p := new(ErrorTokenReason)
	*p = x
	return p
}

func (x ErrorTokenReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorTokenReason) Descriptor() protoreflect.EnumDescriptor {
	return file_token_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorTokenReason) Type() protoreflect.EnumType {
	return &file_token_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorTokenReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorTokenReason.Descriptor instead.
func (ErrorTokenReason) EnumDescriptor() ([]byte, []int) {
	return file_token_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_token_v1_error_reason_proto protoreflect.FileDescriptor

var file_token_v1_error_reason_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2a, 0x29, 0x0a, 0x10, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x11, 0x54,
	0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x42, 0x36, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x50, 0x01,
	0x5a, 0x1b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2d, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0xa2, 0x02, 0x0a,
	0x41, 0x50, 0x49, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_token_v1_error_reason_proto_rawDescOnce sync.Once
	file_token_v1_error_reason_proto_rawDescData = file_token_v1_error_reason_proto_rawDesc
)

func file_token_v1_error_reason_proto_rawDescGZIP() []byte {
	file_token_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_token_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(file_token_v1_error_reason_proto_rawDescData)
	})
	return file_token_v1_error_reason_proto_rawDescData
}

var file_token_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_token_v1_error_reason_proto_goTypes = []interface{}{
	(ErrorTokenReason)(0), // 0: token.v1.ErrorTokenReason
}
var file_token_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_token_v1_error_reason_proto_init() }
func file_token_v1_error_reason_proto_init() {
	if File_token_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_token_v1_error_reason_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_token_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_token_v1_error_reason_proto_enumTypes,
	}.Build()
	File_token_v1_error_reason_proto = out.File
	file_token_v1_error_reason_proto_rawDesc = nil
	file_token_v1_error_reason_proto_goTypes = nil
	file_token_v1_error_reason_proto_depIdxs = nil
}
